var regionesComunas = [
  { region: "Región de Arica y Parinacota", comunas: ["Arica", "Camarones", "Putre", "General Lagos"] },
  { region: "Región de Tarapacá", comunas: ["Iquique", "Alto Hospicio", "Pozo Almonte", "Camiña", "Colchane", "Huara", "Pica"] },
  { region: "Región de Antofagasta", comunas: ["Antofagasta", "Calama", "Tocopilla", "Mejillones", "Sierra Gorda", "Taltal", "María Elena", "Ollagüe", "San Pedro de Atacama"] },
  { region: "Región de Atacama", comunas: ["Copiapó", "Vallenar", "Caldera", "Chañaral", "Diego de Almagro", "Huasco", "Freirina", "Tierra Amarilla"] },
  { region: "Región de Coquimbo", comunas: ["La Serena", "Coquimbo", "Ovalle", "Illapel", "Vicuña", "Salamanca", "Los Vilos", "Andacollo", "Combarbalá", "Monte Patria", "Punitaqui", "Río Hurtado"] },
  { region: "Región de Valparaíso", comunas: ["Valparaíso", "Viña del Mar", "Quilpué", "Villa Alemana", "San Antonio", "San Felipe", "Los Andes", "Quillota", "La Calera", "Limache", "Olmué", "Cabildo", "Calle Larga", "Casablanca", "Concón", "El Quisco", "El Tabo", "Hijuelas", "Isla de Pascua", "Juan Fernández", "La Cruz", "La Ligua", "Llaillay", "Los Andes", "Nogales", "Panquehue", "Papudo", "Petorca", "Puchuncaví", "Putaendo", "Rinconada", "San Esteban", "Santa María", "Santo Domingo", "Valparaíso", "Viña del Mar", "Zapallar"] },
  { region: "Región Metropolitana", comunas: ["Santiago", "Providencia", "Las Condes", "Vitacura", "Lo Barnechea", "Ñuñoa", "La Reina", "Peñalolén", "Macul", "San Miguel", "Pedro Aguirre Cerda", "San Joaquín", "La Cisterna", "El Bosque", "La Pintana", "San Ramón", "Lo Espejo", "Estación Central", "Santiago Centro", "Quinta Normal", "Renca", "Conchalí", "Independencia", "Huechuraba", "Recoleta", "Cerro Navia", "Lo Prado", "Quilicura", "Maipú", "Cerrillos", "Pudahuel", "Padre Hurtado", "Peñaflor", "Talagante", "El Monte", "Isla de Maipo", "Melipilla", "María Pinto", "Curacaví", "Alhué", "San Pedro", "Lampa", "Colina", "Til Til", "Buin", "Paine", "Calera de Tango", "Pirque", "Puente Alto", "La Florida", "San Bernardo", "La Granja", "San José de Maipo"] },
  { region: "Región del Libertador Gral. Bernardo O'Higgins", comunas: ["Rancagua", "San Fernando", "Rengo", "Machalí", "Graneros", "Mostazal", "Codegua", "Doñihue", "Coltauco", "Coínco", "Quinta de Tilcoco", "San Vicente", "Pichidegua", "Peumo", "Las Cabras", "Navidad", "Litueche", "La Estrella", "Pichilemu", "Marchihue", "Pumanque", "Peralillo", "Chépica", "Nancagua", "Placilla", "Chimbarongo", "Lolol", "Santa Cruz", "Palmilla"] },
  { region: "Región del Maule", comunas: ["Talca", "Curicó", "Linares", "Constitución", "San Javier", "Molina", "Cauquenes", "Parral", "Longaví", "Retiro", "Colbún", "San Clemente", "Pelarco", "Río Claro", "Pencahue", "Maule", "Empedrado", "Yerbas Buenas", "Villa Alegre", "Hualañé", "Teno", "Rauco", "Romeral", "Sagrada Familia", "Curepto", "Licantén", "Vichuquén", "Chanco", "Pelluhue"] },
  { region: "Región de Ñuble", comunas: ["Chillán", "Chillán Viejo", "San Carlos", "Quirihue", "Bulnes", "Yungay", "Pemuco", "El Carmen", "Pinto", "San Ignacio", "Ninhue", "Portezuelo", "Ránquil", "Treguaco", "Cobquecura", "Quillón", "Coihueco", "San Nicolás", "Ñiquén"] },
  { region: "Región del Biobío", comunas: ["Concepción", "Talcahuano", "Los Ángeles", "Coronel", "Hualpén", "Chiguayante", "San Pedro de la Paz", "Lota", "Penco", "Tomé", "Arauco", "Lebu", "Curanilahue", "Cañete", "Contulmo", "Tirúa", "Hualqui", "Santa Juana", "Florida", "Yumbel", "Cabrero", "Laja", "San Rosendo", "Quilleco", "Santa Bárbara", "Nacimiento", "Negrete", "Mulchén", "Alto Biobío", "Antuco", "Tucapel", "Los Álamos"] },
  { region: "Región de La Araucanía", comunas: ["Temuco", "Padre Las Casas", "Angol", "Villarrica", "Pucón", "Lautaro", "Victoria", "Nueva Imperial", "Freire", "Pitrufquén", "Gorbea", "Loncoche", "Toltén", "Curarrehue", "Cunco", "Melipeuco", "Vilcún", "Galvarino", "Perquenco", "Cholchol", "Carahue", "Saavedra", "Teodoro Schmidt", "Imperial", "Puerto Saavedra", "Lumaco", "Los Sauces", "Purén", "Traiguén", "Ercilla", "Collipulli", "Curacautín", "Lonquimay"] },
  { region: "Región de Los Ríos", comunas: ["Valdivia", "La Unión", "Río Bueno", "Paillaco", "Futrono", "Lago Ranco", "Máfil", "Lanco", "Panguipulli", "Los Lagos", "Corral"] },
  { region: "Región de Los Lagos", comunas: ["Puerto Montt", "Osorno", "Castro", "Ancud", "Puerto Varas", "Llanquihue", "Frutillar", "Fresia", "Los Muermos", "Maullín", "Calbuco", "Cochamó", "Hualaihué", "Chaitén", "Dalcahue", "Curaco de Vélez", "Quinchao", "Puqueldón", "Chonchi", "Queilén", "Quellón", "Río Negro", "Purranque", "San Pablo", "San Juan de la Costa"] },
  { region: "Región de Aysén del Gral. Carlos Ibáñez del Campo", comunas: ["Coyhaique", "Puerto Aysén", "Chile Chico", "Cochrane", "Río Ibáñez", "Guaitecas", "Lago Verde", "O'Higgins", "Tortel", "Cisnes"] },
  { region: "Región de Magallanes y de la Antártica Chilena", comunas: ["Punta Arenas", "Puerto Natales", "Porvenir", "Navarino", "Primavera", "Timaukel", "San Gregorio", "Río Verde", "Laguna Blanca", "Antártica"] }
];
